# -*- coding: utf-8 -*-
"""Análise de dados com Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vaMQwrJxH73izF_LF16D2JNeux76aLHS
"""

## Importar Pandas para o Vscode

import pandas as pd

##Importar Tabela vendas e visualizar dados

tabela = pd.read_excel('Vendas.xlsx')
display(tabela)

## Exibir faturamento total

Faturamento_total = tabela['Valor Final'].sum()
print (Faturamento_total)

## Faturamento por loja

Faturamento_por_loja = tabela[["ID Loja","Valor Final"]].groupby("ID Loja").sum()
display(Faturamento_por_loja)

#Faturamento por produto

Faturamento_por_produto = tabela[["ID Loja","Produto","Valor Final"]].groupby(["ID Loja","Produto"]).sum()
display(Faturamento_por_produto)